/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.ducko.geesemodpack;

import java.io.IOException;

import javax.swing.JFrame;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

public class App {
	
	private static TaskList tasks;
	//private final static String defaultPath = System.getenv("APPDATA") + "\\.minecraft\\";
	private final static String defaultPath = "C:\\Users\\joemc\\Desktop\\.minecraft\\";
	
    public static void main(String[] args) {
    	System.out.println("hello");
    	Display display = new Display();
    	display.promptWindow(defaultPath);
    }
    
    
}
